const cartActionType = {
    TOGGLE_CART_DROPDOWN_HIDDEN: 'TOGGLE_CART_DROPDOWN_HIDDEN',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_TO_CART: 'REMOVE_ITEM_TO_CART',
    MINUS_QUANTITY_ITEM: 'MINUS_QUANTITY_ITEM'
}

export default cartActionType;